### ISSUE TITLE
Can I use this software for hacking the firmware of Sony video cameras too?

### ISSUE THREAD

**Issue by Cuberlain** [ma1co/qemu#1]
Hello Ma1co!

Can I use this software for hacking the firmware of Sony video cameras too?

**Comment by HoangTheBoss** [comment]
QEMU is a system emulator and has nothing to do with hacking unless you wanted to run Windows on your camera

**Comment by ma1co** [comment]
There are several [supported](https://github.com/ma1co/fwtool.py/blob/master/devices.yml) video cameras.
